# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c56e4c32850f2f43749012621aac0a634b377d148da85a88af95c24a93a6e7cadfd715b43da0d53ac4931e0e234a11444533fbed9f9c068e566bb05508d594c4

test:
  secret_key_base: e4bed849ba180dcc9d4a8dd030442847e105cf5bb1c1cbe25efcc2c94ac7ec60c688459e092e1842b0b8e196138be99ccf79a97d80d958301f1d9a54177ca1d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
